name: ecommerce
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  carousel_slider: ^4.1.1
  dotted_border: ^2.0.0+2
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  shared_preferences: ^2.0.15
  http: ^0.13.4
  dio: ^4.0.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  
  uses-material-design: true


  assets:
    - assets/
    

  